"""3-D parametric geometry + meshing (revolution of the 2-D r-z section).

The full 3-D model is generated by **revolving the same parametric (r, z)
cross-section** used by the axisymmetric builder 360 deg about the vertical
z-axis.  This guarantees the 3-D device is geometrically consistent with the 2-D
model, so:

  * under symmetric (rotationally invariant) excitation the 3-D solution equals
    the axisymmetric one -- the 2-D coax benchmark and CT baseline therefore also
    validate the 3-D model;
  * symmetry-breaking defects (a moisture pocket on one side, a localized
    delamination) can later be injected as genuinely 3-D material patches.

Design notes
------------
* Coordinates: Cartesian (x, y, z); z is the vertical revolution axis.  The
  cylindrical radius is r = hypot(x, y).
* Regions are revolved individually then fragmented into a conformal partition.
  Because a full solid of revolution has its centroid ON the axis, we CANNOT
  classify output volumes by centroid radius; instead we track region identity
  through the boolean via gmsh's fragment out-map and resolve overlaps (foils
  nested in paper) by region priority -- exactly the priority order of
  :func:`ctfem.geometry._ct_regions`.
* Foils are revolved as thin solid shells.  Their 0.15 mm 2-D thickness is
  replaced by ``foil_thickness_3d`` (default 1.5 mm) because thin 3-D shells are
  hostile to the tet mesher and the foil thickness is fictitious anyway (the
  capacitance is set by the foil RADIUS).  See README.
* A reduced ``angle`` (< 2 pi) builds a wedge/sector -- handy for cheap meshing
  experiments on a laptop; the default is a full 360 deg revolve.

This module needs only gmsh + numpy and therefore runs on Windows.  The 3-D EQS
solve still requires DOLFINx (Linux/WSL/HPC) -- see ``eqs_solver3d`` (TODO).
"""
from __future__ import annotations

import json
import math
import os
from dataclasses import replace
from typing import Optional

import gmsh

from .config import GeometryParams
from .geometry import _ct_regions, _point_in_polygon, MeshResult, _Region


def _add_revolved_region(reg: _Region, angle: float) -> list[int]:
    """Build a region face in the x-z plane and revolve it about z; return vols.

    The 2-D classification polygon (r, z) becomes a face at y = 0 with x = r,
    then is revolved ``angle`` radians about the z-axis (point origin, dir +z).
    """
    pts = [gmsh.model.occ.addPoint(r, 0.0, z) for (r, z) in reg.polygon]
    lines = []
    n = len(pts)
    for i in range(n):
        lines.append(gmsh.model.occ.addLine(pts[i], pts[(i + 1) % n]))
    loop = gmsh.model.occ.addCurveLoop(lines)
    face = gmsh.model.occ.addPlaneSurface([loop])
    # revolve about the z-axis (origin, direction +z)
    out = gmsh.model.occ.revolve([(2, face)], 0, 0, 0, 0, 0, 1, angle)
    return [tag for (dim, tag) in out if dim == 3]


def _set_mesh_fields_3d(
    g: GeometryParams,
    region_volumes: dict[str, list[int]],
    foil_surface_tags: list[int],
) -> None:
    """Graded 3-D sizing: per-region point sizes + Distance/Threshold on foils.

    Mirrors the 2-D strategy (gmsh takes the MIN of all size sources): coarse
    point sizes in air, finer in oil/paper, finest on the foil surfaces, with a
    Distance/Threshold background field forcing a thin fine shell around foils.
    """
    ref = max(g.mesh_refinement, 1e-6)
    lc_foil = g.lc_foil / ref
    lc_air = g.lc_air / ref

    gmsh.option.setNumber("Mesh.MeshSizeMin", lc_foil)
    gmsh.option.setNumber("Mesh.MeshSizeMax", lc_air)
    gmsh.option.setNumber("Mesh.MeshSizeExtendFromBoundary", 1)
    gmsh.option.setNumber("Mesh.MeshSizeFromPoints", 1)
    gmsh.option.setNumber("Mesh.MeshSizeFromCurvature", 0)

    from .geometry import _region_lc
    # coarse-first so finer regions win on shared points
    ordered = sorted(region_volumes.items(), key=lambda kv: -_region_lc(kv[0], g))
    for name, tags in ordered:
        lc = _region_lc(name, g) / ref
        pts: set[int] = set()
        for t in tags:
            bnd = gmsh.model.getBoundary([(3, t)], recursive=True, oriented=False)
            for (bdim, btag) in bnd:
                if bdim == 0:
                    pts.add(abs(btag))
        if pts:
            gmsh.model.mesh.setSize([(0, p) for p in pts], lc)

    if not foil_surface_tags:
        return
    dist = gmsh.model.mesh.field.add("Distance")
    gmsh.model.mesh.field.setNumbers(dist, "SurfacesList", foil_surface_tags)
    gmsh.model.mesh.field.setNumber(dist, "Sampling", 100)
    thr = gmsh.model.mesh.field.add("Threshold")
    gmsh.model.mesh.field.setNumber(thr, "InField", dist)
    gmsh.model.mesh.field.setNumber(thr, "SizeMin", lc_foil)
    gmsh.model.mesh.field.setNumber(thr, "SizeMax", lc_air)
    gmsh.model.mesh.field.setNumber(thr, "DistMin", g.refine_dist_min)
    gmsh.model.mesh.field.setNumber(thr, "DistMax", g.refine_dist_max)
    gmsh.model.mesh.field.setAsBackgroundMesh(thr)


def _attach_defect_view(g3, region_volumes, defect, view_path, verbose,
                        matdb=None):
    """Compute the per-cell defect field (reusing apply_defect) and write a gmsh
    'view' so the localized defect can be SEEN in 3-D without any FEM solve.

    Writes a scalar ElementData field = 1.0 on cells altered by the defect, 0.0
    elsewhere. Runs on Windows (numpy only).  Visualization-only -- use a coarse
    mesh; the per-element centroid loop is vectorized but still O(#elements).
    """
    import numpy as np
    from .config import OperatingParams, MaterialParams
    from .materials import MaterialDB
    from . import defects as _defects

    # node-tag -> row lookup table (vectorized centroid computation)
    ntags, ncoords, _ = gmsh.model.mesh.getNodes()
    ncoords = ncoords.reshape(-1, 3)
    lut = np.zeros(int(ntags.max()) + 1, dtype=np.int64)
    lut[ntags.astype(np.int64)] = np.arange(len(ntags))

    elem_ids: list[int] = []
    cents: list[np.ndarray] = []
    regions_pc: list[str] = []
    for name, vols in region_volumes.items():
        for v in vols:
            etypes, etags, enodes = gmsh.model.mesh.getElements(3, v)
            for et, tags, conn in zip(etypes, etags, enodes):
                npe = len(conn) // len(tags)
                idx = lut[conn.astype(np.int64).reshape(len(tags), npe)]
                c = ncoords[idx].mean(axis=1)            # (M,3) centroids
                elem_ids.extend(tags.tolist())
                cents.append(c)
                regions_pc.extend([name] * len(tags))
    centroids = np.vstack(cents)
    region_per_cell = np.array(regions_pc, dtype=object)
    rz = np.column_stack([np.hypot(centroids[:, 0], centroids[:, 1]),
                          centroids[:, 2]])
    theta = np.arctan2(centroids[:, 1], centroids[:, 0])

    op = OperatingParams()
    matdb = matdb or MaterialDB.default()
    # build true baseline per cell, then defect, then indicator
    kmap = matdb.kappa_map(op.omega)
    base = np.array([kmap[_region_material(n)] for n in region_per_cell],
                    dtype=np.complex128)
    after = _defects.apply_defect(defect, rz, region_per_cell, base.copy(),
                                  matdb, op, MaterialParams(), g3, theta=theta)
    indicator = (~np.isclose(after, base, atol=0.0)).astype(float)

    view = gmsh.view.add(f"defect:{defect.label()}")
    gmsh.view.addModelData(
        view, 0, gmsh.model.getCurrent(), "ElementData",
        np.array(elem_ids, dtype=np.int64), indicator.reshape(-1, 1))
    gmsh.view.write(view, view_path)
    if verbose:
        n_hit = int(indicator.sum())
        print(f"[geometry3d] defect '{defect.label()}' touches {n_hit} cells "
              f"-> view {view_path}")


def _region_material(region: str) -> str:
    """Region name -> default material name (mirror of MaterialParams default)."""
    if region.startswith("foil_"):
        return "metal"
    if region.startswith("element_"):
        return "element_dielectric"
    return {"primary_conductor": "metal", "paper_insulation": "paper",
            "oil": "oil", "porcelain": "porcelain", "air": "air",
            "head_housing": "metal", "base_tank": "metal",
            "stack_top": "metal", "stack_bottom": "metal",
            "porcelain_shed": "porcelain"}.get(region, "air")


def build_ct_3d(
    g: GeometryParams,
    out_path: str,
    *,
    angle: float = 2.0 * math.pi,
    defect=None,
    view_path: Optional[str] = None,
    verbose: bool = True,
    gui: bool = False,
    _regions: Optional[list[_Region]] = None,
    _model_name: str = "ct3d",
    _defect_matdb=None,
    _extra_solids=None,
) -> MeshResult:
    """Build and mesh the full 3-D CT (revolved r-z section); write MSH 4.1.

    Parameters
    ----------
    angle : full 2*pi by default; pass a smaller value for a cheap test wedge.

    The underscore parameters let other device builders (:func:`build_cvt_3d`)
    reuse the whole revolve/fragment/tag/mesh pipeline with their own region
    list and material database; `g` then only supplies the mesh-sizing fields
    (duck-typed: lc_*, mesh_refinement, refine_dist_*).
    """
    if _regions is None:
        # use the thicker, mesh-friendly foil annulus for the 3-D revolve
        g3 = replace(g, foil_thickness=g.foil_thickness_3d)
        regions = _ct_regions(g3)
    else:
        g3 = g
        regions = _regions

    gmsh.initialize()
    try:
        gmsh.option.setNumber("General.Terminal", 1 if verbose else 0)
        gmsh.model.add(_model_name)

        # 1. revolve each region -> volume(s); remember source region index
        vol_to_region_idx: dict[int, int] = {}
        input_dimtags: list[tuple[int, int]] = []
        src_index_of_vol: dict[int, int] = {}
        region_vol_inputs: list[list[int]] = []
        for idx, reg in enumerate(regions):
            vols = _add_revolved_region(reg, angle)
            region_vol_inputs.append(vols)
            for v in vols:
                input_dimtags.append((3, v))
                src_index_of_vol[v] = idx

        # non-axisymmetric attachments (e.g. the CVT secondary terminal box):
        # a callable building OCC volumes -> [(region_name, vol_tag)]; they join
        # the fragment like any revolved volume and inherit that region's tag.
        if _extra_solids is not None:
            name_to_idx: dict[str, int] = {}
            for i, r in enumerate(regions):
                name_to_idx.setdefault(r.name, i)
            for name, vtag in _extra_solids():
                input_dimtags.append((3, vtag))
                src_index_of_vol[vtag] = name_to_idx[name]
        gmsh.model.occ.synchronize()

        # 2. fragment all volumes into a conformal partition; track provenance
        out, outmap = gmsh.model.occ.fragment(input_dimtags, [])
        gmsh.model.occ.synchronize()

        # outmap aligns with input_dimtags order; each entry lists child vols.
        # A child shared by several inputs (foil inside paper) gets the
        # highest-priority (lowest-index) source region.
        child_region_idx: dict[int, int] = {}
        for in_pos, children in enumerate(outmap):
            src_vol = input_dimtags[in_pos][1]
            ridx = src_index_of_vol[src_vol]
            for (cdim, ctag) in children:
                if cdim != 3:
                    continue
                if ctag not in child_region_idx or ridx < child_region_idx[ctag]:
                    child_region_idx[ctag] = ridx

        # group surviving volumes by region name
        region_volumes: dict[str, list[int]] = {}
        for (dim, tag) in gmsh.model.getEntities(3):
            ridx = child_region_idx.get(tag)
            name = regions[ridx].name if ridx is not None else "air"
            region_volumes.setdefault(name, []).append(tag)

        # 3. physical volume groups
        for name, tags in region_volumes.items():
            pg = gmsh.model.addPhysicalGroup(3, tags)
            gmsh.model.setPhysicalName(3, pg, name)

        # 4. surface adjacency -> electrode / farfield / foil-surface tagging
        vol_name_of_tag: dict[int, str] = {}
        for name, tags in region_volumes.items():
            for t in tags:
                vol_name_of_tag[t] = name
        surf_to_vols: dict[int, list[str]] = {}
        for (dim, tag) in gmsh.model.getEntities(3):
            for (bdim, btag) in gmsh.model.getBoundary([(3, tag)], oriented=False):
                surf_to_vols.setdefault(abs(btag), []).append(vol_name_of_tag[tag])

        hv_names = {r.name for r in regions if r.is_hv_metal}
        gnd_names = {r.name for r in regions if r.is_ground_metal}
        foil_names = {r.name for r in regions if r.name.startswith("foil_")}

        hv_s, gnd_s, ff_s, foil_s = [], [], [], []
        is_full = angle >= 2.0 * math.pi - 1e-9
        for stag, neigh in surf_to_vols.items():
            ns = set(neigh)
            if (ns & hv_names) and (ns - hv_names):
                hv_s.append(stag)
            if (ns & gnd_names) and (ns - gnd_names):
                gnd_s.append(stag)
            if ns & foil_names:
                foil_s.append(stag)
            # far field = air's only EXTERNAL boundary (single adjacent volume).
            # NB: the outer cylinder surface is symmetric so its centroid lies on
            # the axis -- do NOT filter on centroid radius (that was a bug).
            if len(neigh) == 1 and neigh[0] == "air":
                ff_s.append(stag)
        if not is_full and verbose:
            print("[geometry3d] WARNING: wedge mode (angle < 2pi) -- the theta "
                  "symmetry planes are lumped into 'farfield'. Wedge meshes are "
                  "for visualization only; solve on a full 2pi revolve.")

        def _add_surf_group(name: str, tags: list[int]) -> None:
            if tags:
                pg = gmsh.model.addPhysicalGroup(2, sorted(set(tags)))
                gmsh.model.setPhysicalName(2, pg, name)

        _add_surf_group("hv_electrode", hv_s)
        _add_surf_group("ground_electrode", gnd_s)
        _add_surf_group("farfield", ff_s)
        _add_surf_group("foil_surfaces", foil_s)

        # 5. mesh sizing + generate
        _set_mesh_fields_3d(g3, region_volumes, foil_s if foil_names else [])
        gmsh.option.setNumber("Mesh.MshFileVersion", 4.1)
        # binary MSH: ~5x faster to parse with meshio (3-D meshes are large)
        gmsh.option.setNumber("Mesh.Binary", 1)
        gmsh.model.mesh.generate(3)

        # 6. verify non-empty groups + stats + tag sidecar
        vol_counts: dict[str, int] = {}
        surf_counts: dict[str, int] = {}
        physical_tags: dict[str, tuple[int, int]] = {}
        for (dim, pg) in gmsh.model.getPhysicalGroups():
            nm = gmsh.model.getPhysicalName(dim, pg)
            physical_tags[nm] = (dim, pg)
            n_elem = 0
            for e in gmsh.model.getEntitiesForPhysicalGroup(dim, pg):
                _, etags, _ = gmsh.model.mesh.getElements(dim, e)
                n_elem += sum(len(t) for t in etags)
            if dim == 3:
                vol_counts[nm] = n_elem
            elif dim == 2:
                surf_counts[nm] = n_elem
            if n_elem == 0:
                raise RuntimeError(f"physical group {nm!r} (dim {dim}) is EMPTY")

        node_tags, _, _ = gmsh.model.mesh.getNodes()
        n_nodes = len(node_tags)
        _, tet_tags, _ = gmsh.model.mesh.getElements(3)
        n_tet = sum(len(t) for t in tet_tags)

        gmsh.write(out_path)
        sidecar = os.path.splitext(out_path)[0] + ".tags.json"
        with open(sidecar, "w") as fh:
            json.dump({k: list(v) for k, v in physical_tags.items()}, fh, indent=2)
        if verbose:
            print(f"[geometry3d] wrote {out_path}: {n_nodes} nodes, {n_tet} tets")

        # optional: overlay a localized-defect indicator field (no solve needed)
        if defect is not None and not getattr(defect, "kind", "none") == "none":
            vp = view_path or (os.path.splitext(out_path)[0] + "_defect.pos")
            _attach_defect_view(g3, region_volumes, defect, vp, verbose,
                                matdb=_defect_matdb)

        if gui:  # pragma: no cover
            gmsh.fltk.run()

        # MeshResult fields are generic (surface/curve groups) -- reuse them for
        # (volume groups / surface groups) in 3-D.
        return MeshResult(out_path, vol_counts, surf_counts, n_nodes, n_tet,
                          physical_tags)
    finally:
        gmsh.finalize()


def build_cvt_3d(
    c,
    out_path: str,
    *,
    angle: float = 2.0 * math.pi,
    defect=None,
    view_path: Optional[str] = None,
    verbose: bool = True,
    gui: bool = False,
) -> MeshResult:
    """Build and mesh the full 3-D CVT (revolved DDB-style r-z section).

    `c` is a :class:`ctfem.config.CVTParams`.  The electrode discs are already
    6 mm thick (mesh-friendly), so no 3-D thickness substitution is needed.
    The secondary terminal box (c.secondary_box) breaks rotational symmetry,
    so it exists ONLY here: it is unioned into the grounded tank via the
    extra-solids hook (the 2-D axisymmetric model cannot represent it).
    """
    from .geometry import _cvt_regions

    def _secondary_box():
        if not c.secondary_box:
            return []
        # protrude radially from the tank wall (overlap 20 mm into the tank so
        # the fragment fuses them); grounded metal like the tank itself
        tag = gmsh.model.occ.addBox(
            c.tank_radius - 0.020, -0.5 * c.secondary_box_width,
            c.secondary_box_z0,
            c.secondary_box_depth + 0.020, c.secondary_box_width,
            c.secondary_box_height)
        return [("base_tank", tag)]

    return build_ct_3d(
        c, out_path, angle=angle, defect=defect, view_path=view_path,
        verbose=verbose, gui=gui,
        _regions=_cvt_regions(c), _model_name="cvt3d",
        _defect_matdb=c.material_db(), _extra_solids=_secondary_box)
